# Generated by Django 3.0 on 2022-09-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca_valores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banca_valor',
            options={'verbose_name': 'Banca', 'verbose_name_plural': ('Bancas',)},
        ),
        migrations.AlterModelTable(
            name='banca_valor',
            table='banca_valor',
        ),
    ]
