# Generated by Django 3.0 on 2022-09-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca_valores', '0002_auto_20220927_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banca_valor',
            name='banca',
        ),
    ]
