# Generated by Django 3.0 on 2022-09-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banca_valores', '0003_remove_banca_valor_banca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banca_valor',
            options={'verbose_name': 'Banca valor', 'verbose_name_plural': ('Bancas valores',)},
        ),
    ]
