# Generated by Django 3.0 on 2022-10-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banca_nome', models.CharField(max_length=100, verbose_name='Nome da Banca')),
                ('banca_valor', models.DecimalField(decimal_places=2, max_digits=25, max_length=50, verbose_name='Valor da Banca hoje R$')),
            ],
            options={
                'verbose_name': ('Banca',),
                'verbose_name_plural': ('Bancas',),
                'db_table': 'dinheiro',
            },
        ),
    ]
