# Generated by Django 3.0 on 2022-09-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_casa', models.CharField(max_length=194, verbose_name='Time joganfo em casa')),
                ('time_fora', models.CharField(max_length=194, verbose_name='Time joganfo fora')),
                ('valor_aposta', models.IntegerField(verbose_name='Valor apostado R$')),
                ('cotacao', models.FloatField(verbose_name='Cotação')),
                ('horario_aposta', models.DateTimeField(auto_now_add=True, verbose_name='Horario aposta')),
                ('banca_apostada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bancas.Banca', verbose_name='Banca que aconteceu a aposta')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': ('Bilhetes',),
                'db_table': 'bilhete',
            },
        ),
    ]
