# Generated by Django 3.0 on 2022-09-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilhetes', '0002_auto_20220917_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilhete',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('GREEN', 'Green'), ('RED', 'Red')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
