# Generated by Django 3.0 on 2022-09-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilhetes', '0003_bilhete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('GREEN', 'Green'), ('RED', 'Red')], default='AGUARDANDO', max_length=11, verbose_name='status'),
        ),
    ]
