# Generated by Django 3.0 on 2022-09-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banca', models.CharField(max_length=100, verbose_name='Nome da Banca: ')),
                ('valor_inicial_banca', models.IntegerField(verbose_name='Valor inicial da banca')),
                ('data_inicio_banca', models.DateTimeField(auto_now_add=True, verbose_name='Data inicio banca')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Banca',
                'verbose_name_plural': 'Bancas',
                'db_table': 'banca',
            },
        ),
    ]
