# Generated by Django 3.0 on 2022-10-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banca',
            name='usuario',
        ),
    ]
